version: "3.8"
services:
  app:
    build: ./docker/app
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    command: /bin/sh -c "tail -f /dev/null"
    depends_on:
      - db

  db:
    build: ./docker/database/
    platform: linux/amd64
    ports:
      - 3306:3306